karticky = {
    "postuponost": ["Prva orazova Ulica", "Druha orazova Ulica", "Pokladna1", "Tretia orazova ulica", "zeleznica1",
                    "Prva ruzova ulica", "Druha ruzova ulica", "Energeticke zavody", "Tretia ruzova ulica",
                    "Prva svetlomodra ulica",
                    "Druha svetlomodra ulica", "Sanca1", "Tretia svetlomodra ulica", "zeleznica2", "Dan200",
                    "Prva hneda ulica",
                    "Pokladna2", "Druha hneda ulica", "Prva modra ulica",
                    "Dan100", "Druha modra ulica", "Sanca2", "zeleznica3", "Prva zelena ulica", "Pokladna3",
                    "Druha zelena ulica",
                    "Tretia zelena ulica", "Prva zlta ulica", "Vodarne", "Druha zlta ulica", "Tretia zlta ulica",
                    "zeleznica4",
                    "Prva cervena ulica", "Druha cervena ulica", "Sanca3", "Tretia cervena ulica", ],
    "postuponost2": ["Prva orazova Ulica", "Druha orazova Ulica", "Pokladna1", "Tretia orazova ulica", "zeleznica1",
                     "Prva ruzova ulica", "Druha ruzova ulica", "Energeticke zavody", "Tretia ruzova ulica", "Vezenie",
                     "Prva svetlomodra ulica", "Druha svetlomodra ulica", "Sanca1", "Tretia svetlomodra ulica",
                     "zeleznica2", "Dan200",
                     "Prva hneda ulica",
                     "Pokladna2", "Druha hneda ulica", "Start", "Prva modra ulica",
                     "Dan100", "Druha modra ulica", "Sanca2", "zeleznica3", "Prva zelena ulica", "Pokladna3",
                     "Druha zelena ulica",
                     "Tretia zelena ulica", "Chod do vezenia", "Prva zlta ulica", "Vodarne", "Druha zlta ulica",
                     "Tretia zlta ulica",
                     "zeleznica4",
                     "Prva cervena ulica", "Druha cervena ulica", "Sanca3", "Tretia cervena ulica", "Free wifi"],
    "Start": {"Nazov": "Štart",
              "Text karticka": "Pri prechode poličkom štart sa ti pripíše 200$",
              "Hodnota": 200
        , "kolkostoji": 0},
    "Prva orazova Ulica": {"Nazov": "Dostojevskeho rad",
                           "Nakupna cena": 180,
                           "Hypoteka": 90,
                           "Cena domu": 100,
                           "Cena Hotelu": 100,
                           "Zakladne najomne": 14,
                           "1 dom": 70,
                           "2 domy": 200,
                           "3 domy": 550,
                           "4 domy ": 750,
                           "Hotel": 950,
                           "Farba": "DarkOrange1",
                           "kolkostoji": 0

                           },
    "Druha orazova Ulica": {"Nazov": "Šturova ulica",
                            "Nakupna cena": 180,
                            "Hypoteka": 90,
                            "Cena domu": 100,
                            "Cena Hotelu": 100,
                            "Zakladne najomne": 14,
                            "1 dom": 70,
                            "2 domy": 200,
                            "3 domy": 550,
                            "4 domy ": 750,
                            "Hotel": 950,
                            "Farba": "DarkOrange1",
                            "kolkostoji": 0
                            },
    "Tretia orazova ulica": {"Nazov": "Dostojovskeho ulica",
                             "Nakupna cena": 180,
                             "Hypoteka": 100,
                             "Cena domu": 100,
                             "Cena Hotelu": 100,
                             "Zakladne najomne": 16,
                             "1 dom": 80,
                             "2 domy": 200,
                             "3 domy": 600,
                             "4 domy ": 800,
                             "Hotel": 1000,
                             "Farba": "DarkOrange1",
                             "kolkostoji": 0},
    "Prva ruzova ulica": {"Nazov": "Vajanskeho nabrezie",
                          "Nakupna cena": 160,
                          "Hypoteka": 80,
                          "Cena domu": 100,
                          "Cena Hotelu": 100,
                          "Zakladne najomne": 12,
                          "1 dom": 60,
                          "2 domy": 180,
                          "3 domy": 500,
                          "4 domy ": 700,
                          "Hotel": 900,
                          "Farba": "deeppink",
                          "kolkostoji": 0},
    "Druha ruzova ulica": {"Nazov": "Razusovo nabrežie",
                           "Nakupna cena": 140,
                           "Hypoteka": 70,
                           "Cena domu": 100,
                           "Cena Hotelu": 100,
                           "Zakladne najomne": 10,
                           "1 dom": 50,
                           "2 domy": 150,
                           "3 domy": 450,
                           "4 domy ": 625,
                           "Hotel": 750,
                           "Farba": "deeppink",
                           "kolkostoji": 0},
    "Tretia ruzova ulica": {"Nazov": "Spitalska ulica",
                            "Nakupna cena": 140,
                            "Hypoteka": 70,
                            "Cena domu": 100,
                            "Cena Hotelu": 100,
                            "Zakladne najomne": 10,
                            "1 dom": 50,
                            "2 domy": 150,
                            "3 domy": 450,
                            "4 domy ": 625,
                            "Hotel": 750,
                            "Farba": "deeppink",
                            "kolkostoji": 0},
    "Prva svetlomodra ulica": {"Nazov": "Zahradnicka ulica",
                               "Nakupna cena": 120,
                               "Hypoteka": 60,
                               "Cena domu": 50,
                               "Cena Hotelu": 50,
                               "Zakladne najomne": 8,
                               "1 dom": 40,
                               "2 domy": 100,
                               "3 domy": 300,
                               "4 domy ": 450,
                               "Hotel": 600,
                               "Farba": "deep sky blue",
                               "kolkostoji": 0},
    "Druha svetlomodra ulica": {"Nazov": "Karadžičova ulica",
                                "Nakupna cena": 100,
                                "Hypoteka": 50,
                                "Cena domu": 50,
                                "Cena Hotelu": 50,
                                "Zakladne najomne": 6,
                                "1 dom": 30,
                                "2 domy": 90,
                                "3 domy": 270,
                                "4 domy ": 400,
                                "Hotel": 550,
                                "Farba": "deep sky blue",
                                "kolkostoji": 0},
    "Tretia svetlomodra ulica": {"Nazov": "Dunajska ulica",
                                 "Nakupna cena": 120,
                                 "Hypoteka": 50,
                                 "Cena domu": 50,
                                 "Cena Hotelu": 50,
                                 "Zakladne najomne": 6,
                                 "1 dom": 30,
                                 "2 domy": 90,
                                 "3 domy": 270,
                                 "4 domy ": 400,
                                 "Hotel": 550,
                                 "Farba": "deep sky blue",
                                 "kolkostoji": 0},
    "Prva hneda ulica": {"Nazov": "Panská ulica",
                         "Nakupna cena": 60,
                         "Hypoteka": 30,
                         "Cena domu": 50,
                         "Cena Hotelu": 50,
                         "Zakladne najomne": 4,
                         "1 dom": 20,
                         "2 domy": 60,
                         "3 domy": 180,
                         "4 domy ": 320,
                         "Hotel": 450,
                         "Farba": "brown",
                         "kolkostoji": 0},
    "Druha hneda ulica": {"Nazov": "Zochova ulica",
                          "Nakupna cena": 60,
                          "Hypoteka": 30,
                          "Cena domu": 50,
                          "Cena Hotelu": 50,
                          "Zakladne najomne": 2,
                          "1 dom": 10,
                          "2 domy": 30,
                          "3 domy": 90,
                          "4 domy ": 160,
                          "Hotel": 250,
                          "Farba": "brown",
                          "kolkostoji": 0},
    "Prva modra ulica": {"Nazov": "Hlavne namestie",
                         "Nakupna cena": 400,
                         "Hypoteka": 200,
                         "Cena domu": 200,
                         "Cena Hotelu": 200,
                         "Zakladne najomne": 50,
                         "1 dom": 200,
                         "2 domy": 600,
                         "3 domy": 1400,
                         "4 domy ": 1700,
                         "Hotel": 2000,
                         "Farba": "darkblue",
                         "kolkostoji": 0},
    "Druha modra ulica": {"Nazov": "Obchodna ulica",
                          "Nakupna cena": 350,
                          "Hypoteka": 175,
                          "Cena domu": 200,
                          "Cena Hotelu": 200,
                          "Zakladne najomne": 35,
                          "1 dom": 175,
                          "2 domy": 500,
                          "3 domy": 1100,
                          "4 domy ": 1300,
                          "Hotel": 1500,
                          "Farba": "darkblue",
                          "kolkostoji": 0},
    "Prva zelena ulica": {"Nazov": "Einsteinova "
                                   "ulica",
                          "Nakupna cena": 320,
                          "Hypoteka": 160,
                          "Cena domu": 200,
                          "Cena Hotelu": 200,
                          "Zakladne najomne": 28,
                          "1 dom": 150,
                          "2 domy": 450,
                          "3 domy": 1000,
                          "4 domy ": 1200,
                          "Hotel": 1400,
                          "Farba": "green",
                          "kolkostoji": 0},
    "Druha zelena ulica": {"Nazov": "Mlynske "
                                    "nivy",
                           "Nakupna cena": 300,
                           "Hypoteka": 150,
                           "Cena domu": 200,
                           "Cena Hotelu": 200,
                           "Zakladne najomne": 26,
                           "1 dom": 130,
                           "2 domy": 390,
                           "3 domy": 900,
                           "4 domy ": 1100,
                           "Hotel": 1275,
                           "Farba": "green",
                           "kolkostoji": 0},
    "Tretia zelena ulica": {"Nazov": "Americke namestie",
                            "Nakupna cena": 300,
                            "Hypoteka": 150,
                            "Cena domu": 200,
                            "Cena Hotelu": 200,
                            "Zakladne najomne": 26,
                            "1 dom": 130,
                            "2 domy": 390,
                            "3 domy": 900,
                            "4 domy ": 1100,
                            "Hotel": 1275,
                            "Farba": "green",
                            "kolkostoji": 0},
    "Prva zlta ulica": {"Nazov": "Florianske "
                                 "namestie",
                        "Nakupna cena": 280,
                        "Hypoteka": 140,
                        "Cena domu": 150,
                        "Cena Hotelu": 150,
                        "Zakladne najomne": 24,
                        "1 dom": 120,
                        "2 domy": 360,
                        "3 domy": 850,
                        "4 domy ": 1025,
                        "Hotel": 1200,
                        "Farba": "DarkGoldenrod2",
                        "kolkostoji": 0},
    "Druha zlta ulica": {"Nazov": "Košicka ulica",
                         "Nakupna cena": 260,
                         "Hypoteka": 130,
                         "Cena domu": 150,
                         "Cena Hotelu": 150,
                         "Zakladne najomne": 22,
                         "1 dom": 110,
                         "2 domy": 330,
                         "3 domy": 800,
                         "4 domy ": 975,
                         "Hotel": 1150,
                         "Farba": "DarkGoldenrod2",
                         "kolkostoji": 0},
    "Tretia zlta ulica": {"Nazov": "Račianska ulica",
                          "Nakupna cena": 260,
                          "Hypoteka": 130,
                          "Cena domu": 150,
                          "Cena Hotelu": 150,
                          "Zakladne najomne": 22,
                          "1 dom": 110,
                          "2 domy": 330,
                          "3 domy": 800,
                          "4 domy ": 975,
                          "Hotel": 1050,
                          "Farba": "DarkGoldenrod2",
                          "kolkostoji": 0},
    "Prva cervena ulica": {"Nazov": "Palisady",
                           "Nakupna cena": 240,
                           "Hypoteka": 120,
                           "Cena domu": 150,
                           "Cena Hotelu": 150,
                           "Zakladne najomne": 20,
                           "1 dom": 100,
                           "2 domy": 300,
                           "3 domy": 750,
                           "4 domy ": 925,
                           "Hotel": 1100,
                           "Farba": "red",
                           "kolkostoji": 0},
    "Druha cervena ulica": {"Nazov": "Vajnorska Ulica",
                            "Nakupna cena": 220,
                            "Hypoteka": 110,
                            "Cena domu": 150,
                            "Cena Hotelu": 150,
                            "Zakladne najomne": 18,
                            "1 dom": 90,
                            "2 domy": 250,
                            "3 domy": 700,
                            "4 domy ": 875,
                            "Hotel": 1050,
                            "Farba": "red",
                            "kolkostoji": 0},
    "Tretia cervena ulica": {"Nazov": "Šancova ulica",
                             "Nakupna cena": 220,
                             "Hypoteka": 110,
                             "Cena domu": 150,
                             "Cena Hotelu": 150,
                             "Zakladne najomne": 18,
                             "1 dom": 90,
                             "2 domy": 250,
                             "3 domy": 700,
                             "4 domy ": 875,
                             "Hotel": 1050,
                             "Farba": "red",
                             "kolkostoji": 0},
    "Pokladna1": {"Nazov": "Pokladňa",
                  "Farba": None,
                  "Nakupna cena": None,
                  "Image": r"B_pay.png",
                  "kolkostoji": 0},
    "Pokladna2": {"Nazov": "Pokladňa",
                  "Farba": None,
                  "Nakupna cena": None,
                  "Image": r"B_pay.png",
                  "kolkostoji": 0},
    "Pokladna3": {"Nazov": "Pokladňa",
                  "Farba": None,
                  "Nakupna cena": None,
                  "Image": r"B_pay.png",
                  "kolkostoji": 0},
    "zeleznica1": {"Nazov": "Hlavna stanica",
                   "Nakupna cena": 200,
                   "Hypoteka": 100,
                   "Zakladne najomne": 16,
                   "Ak vlastni 2": 50,
                   "Ak vlastni 3": 100,
                   "Ak vlastni 4": 200,
                   "Farba": None,
                   "Image": r"vlak.png",
                   "kolkostoji": 0
                   },
    "zeleznica2": {"Nazov": "Vinohrady",
                   "Nakupna cena": 200,
                   "Hypoteka": 100,
                   "Zakladne najomne": 16,
                   "Ak vlastni 2": 50,
                   "Ak vlastni 3": 100,
                   "Ak vlastni 4": 200,
                   "Farba": None,
                   "Image": r"vlak.png",
                   "kolkostoji": 0
                   },
    "zeleznica3": {"Nazov": "Peržalka",
                   "Nakupna cena": 200,
                   "Hypoteka": 100,
                   "Zakladne najomne": 16,
                   "Ak vlastni 2": 50,
                   "Ak vlastni 3": 100,
                   "Ak vlastni 4": 200,
                   "Farba": None,
                   "Image": r"vlak.png",
                   "kolkostoji": 0
                   },
    "zeleznica4": {"Nazov": "Nové mesto",
                   "Nakupna cena": 200,
                   "Hypoteka": 100,
                   "Zakladne najomne": 16,
                   "Ak vlastni 2": 50,
                   "Ak vlastni 3": 100,
                   "Ak vlastni 4": 200,
                   "Farba": None,
                   "Image": r"vlak.png",
                   "kolkostoji": 0
                   },
    "Energeticke zavody": {"Nazov": "Energeticke zavody",
                           "Nakupna cena": 150,
                           "Hypoteka": 75,
                           "Farba": None,
                           "popis": "Ak hráč vlastní jeden podnik verejných služieb, najomné je štvornasobok hodu obidvoch kociek. "
                                    " Ak hráč vlastní OBIDVA podniky verejných služieb, nájomné je desaťnasobok hodu obidvoch kociek. ",
                           "Ak vlastni 1 nasobok": 4,
                           "Ak vlastni obe nasobok": 10,
                           "Image": r"elektro.png",
                           "kolkostoji": 0
                           },
    "Sanca1": {"Nazov": "Šanca",
               "Farba": None,
               "Nakupna cena": None,
               "Image": r"otaznik.png",
               "kolkostoji": 0

               },
    "Sanca2": {"Nazov": "Šanca",
               "Farba": None,
               "Nakupna cena": None,
               "Image": r"otaznik.png",
               "kolkostoji": 0

               },
    "Sanca3": {"Nazov": "Šanca",
               "Farba": None,
               "Nakupna cena": None,
               "Image": r"otaznik.png"
        , "kolkostoji": 0

               },
    "Dan200": {"Nazov": "Daň z prímu",
               "Farba": None,
               "Nakupna cena": None,
               "Zakladne najomne": 200,
               "Image": None, "kolkostoji": 0
               },
    "Dan100": {"Nazov": "Daň z prímu",
               "Farba": None,
               "Nakupna cena": None,
               "Zakladne najomne": 100,
               "Image": None
        , "kolkostoji": 0
               },
    "Vodarne": {"Nazov": "Vodarne",
                "Nakupna cena": 150,
                "Hypoteka": 75,
                "Farba": None,
                "popis": "Ak hráč vlastní jeden podnik verejných služieb, naájomné je štvornasobok hodu obidvoch kociek."
                         "Ak hráč vlastní OBIDVA podniky verejných služieb, nájomné je desaťnasobok hodu obidvoch kociek. ",
                "Ak vlastni 1 nasobok": 4,
                "Ak vlastni obe nasobok": 10,
                "Image": r"kohutik.png"
        , "kolkostoji": 0
                },
    "Vezenie": {"Nazov": "Vezenie", "kolkostoji": 0},
    "Free wifi": {"Nazov": "Free wifi", "kolkostoji": 0},
    "Chod do vezenia": {"Nazov": "Chod do vezenia", "kolkostoji": 0},
}

import json

with open('subor.txt', 'w') as subor:
    json.dump(karticky, subor, indent=4)
